In [1]:
import numpy as np
import torch
import pandas as pd


In [2]:
df = pd.read_csv('./iris.csv')
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [5]:
X=df.drop('target', axis=1).values
y=df['target'].values

In [4]:
from torch.utils.data import TensorDataset, DataLoader
help(TensorDataset)

Help on class TensorDataset in module torch.utils.data.dataset:

class TensorDataset(Dataset)
 |  TensorDataset(*tensors: torch.Tensor) -> None
 |  
 |  Dataset wrapping tensors.
 |  
 |  Each sample will be retrieved by indexing tensors along the first dimension.
 |  
 |  Args:
 |      *tensors (Tensor): tensors that have the same size of the first dimension.
 |  
 |  Method resolution order:
 |      TensorDataset
 |      Dataset
 |      typing.Generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __getitem__(self, index)
 |  
 |  __init__(self, *tensors: torch.Tensor) -> None
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __len__(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  __annotations__ = {'tensors': typing.Tuple[torch.Tensor, ...]}
 |  
 |  __orig_bases__ = (torch.utils.data.dataset.Dataset[typing.Tuple[torch....
 |  
 |  __parameters__ 

In [8]:
iris = TensorDataset(torch.FloatTensor(X), torch.FloatTensor(y))
iris.tensors

(tensor([[5.1000, 3.5000, 1.4000, 0.2000],
         [4.9000, 3.0000, 1.4000, 0.2000],
         [4.7000, 3.2000, 1.3000, 0.2000],
         [4.6000, 3.1000, 1.5000, 0.2000],
         [5.0000, 3.6000, 1.4000, 0.2000],
         [5.4000, 3.9000, 1.7000, 0.4000],
         [4.6000, 3.4000, 1.4000, 0.3000],
         [5.0000, 3.4000, 1.5000, 0.2000],
         [4.4000, 2.9000, 1.4000, 0.2000],
         [4.9000, 3.1000, 1.5000, 0.1000],
         [5.4000, 3.7000, 1.5000, 0.2000],
         [4.8000, 3.4000, 1.6000, 0.2000],
         [4.8000, 3.0000, 1.4000, 0.1000],
         [4.3000, 3.0000, 1.1000, 0.1000],
         [5.8000, 4.0000, 1.2000, 0.2000],
         [5.7000, 4.4000, 1.5000, 0.4000],
         [5.4000, 3.9000, 1.3000, 0.4000],
         [5.1000, 3.5000, 1.4000, 0.3000],
         [5.7000, 3.8000, 1.7000, 0.3000],
         [5.1000, 3.8000, 1.5000, 0.3000],
         [5.4000, 3.4000, 1.7000, 0.2000],
         [5.1000, 3.7000, 1.5000, 0.4000],
         [4.6000, 3.6000, 1.0000, 0.2000],
         [5

In [9]:
len(iris)

150

In [10]:
for i in iris:
    print(i)

(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0.))
(tensor([4.9000, 3.0000, 1.4000, 0.2000]), tensor(0.))
(tensor([4.7000, 3.2000, 1.3000, 0.2000]), tensor(0.))
(tensor([4.6000, 3.1000, 1.5000, 0.2000]), tensor(0.))
(tensor([5.0000, 3.6000, 1.4000, 0.2000]), tensor(0.))
(tensor([5.4000, 3.9000, 1.7000, 0.4000]), tensor(0.))
(tensor([4.6000, 3.4000, 1.4000, 0.3000]), tensor(0.))
(tensor([5.0000, 3.4000, 1.5000, 0.2000]), tensor(0.))
(tensor([4.4000, 2.9000, 1.4000, 0.2000]), tensor(0.))
(tensor([4.9000, 3.1000, 1.5000, 0.1000]), tensor(0.))
(tensor([5.4000, 3.7000, 1.5000, 0.2000]), tensor(0.))
(tensor([4.8000, 3.4000, 1.6000, 0.2000]), tensor(0.))
(tensor([4.8000, 3.0000, 1.4000, 0.1000]), tensor(0.))
(tensor([4.3000, 3.0000, 1.1000, 0.1000]), tensor(0.))
(tensor([5.8000, 4.0000, 1.2000, 0.2000]), tensor(0.))
(tensor([5.7000, 4.4000, 1.5000, 0.4000]), tensor(0.))
(tensor([5.4000, 3.9000, 1.3000, 0.4000]), tensor(0.))
(tensor([5.1000, 3.5000, 1.4000, 0.3000]), tensor(0.))
(tensor([5

In [11]:
#batches we use DataLoader
iris_loader = DataLoader(iris,batch_size=50,shuffle=True)

for batch_no, batch in enumerate(iris_loader):
    print(batch_no,'    ', batch)

0      [tensor([[5.7000, 4.4000, 1.5000, 0.4000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [6.5000, 2.8000, 4.6000, 1.5000],
        [6.7000, 3.1000, 4.7000, 1.5000],
        [5.6000, 3.0000, 4.1000, 1.3000],
        [6.2000, 3.4000, 5.4000, 2.3000],
        [6.3000, 3.4000, 5.6000, 2.4000],
        [7.0000, 3.2000, 4.7000, 1.4000],
        [5.0000, 3.2000, 1.2000, 0.2000],
        [6.4000, 3.1000, 5.5000, 1.8000],
        [6.7000, 3.3000, 5.7000, 2.5000],
        [5.6000, 2.9000, 3.6000, 1.3000],
        [5.0000, 2.0000, 3.5000, 1.0000],
        [6.5000, 3.2000, 5.1000, 2.0000],
        [5.1000, 2.5000, 3.0000, 1.1000],
        [5.8000, 2.7000, 5.1000, 1.9000],
        [6.4000, 3.2000, 4.5000, 1.5000],
        [6.9000, 3.1000, 5.1000, 2.3000],
        [5.4000, 3.9000, 1.3000, 0.4000],
        [5.4000, 3.7000, 1.5000, 0.2000],
        [6.4000, 3.2000, 5.3000, 2.3000],
        [4.9000, 2.5000, 4.5000, 1.7000],
        [6.0000, 2.2000, 4.0000, 1.0000],
        [6.6000, 2.9000, 4

In [16]:
list(iris_loader)[0][1]

tensor([0., 1., 2., 2., 0., 0., 2., 1., 0., 2., 1., 0., 2., 1., 2., 1., 0., 0.,
        2., 2., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 2., 0., 2., 0., 1., 1.,
        2., 0., 2., 1., 0., 0., 2., 2., 1., 0., 1., 0., 2., 2.])

In [18]:
next(iter(iris_loader))

[tensor([[7.0000, 3.2000, 4.7000, 1.4000],
         [6.0000, 2.7000, 5.1000, 1.6000],
         [5.9000, 3.0000, 4.2000, 1.5000],
         [6.7000, 2.5000, 5.8000, 1.8000],
         [6.2000, 2.9000, 4.3000, 1.3000],
         [4.6000, 3.1000, 1.5000, 0.2000],
         [5.4000, 3.9000, 1.3000, 0.4000],
         [7.3000, 2.9000, 6.3000, 1.8000],
         [5.0000, 2.3000, 3.3000, 1.0000],
         [6.5000, 3.0000, 5.5000, 1.8000],
         [4.7000, 3.2000, 1.3000, 0.2000],
         [6.1000, 3.0000, 4.9000, 1.8000],
         [7.6000, 3.0000, 6.6000, 2.1000],
         [6.1000, 2.6000, 5.6000, 1.4000],
         [6.9000, 3.1000, 5.4000, 2.1000],
         [6.8000, 2.8000, 4.8000, 1.4000],
         [6.0000, 3.4000, 4.5000, 1.6000],
         [6.3000, 3.3000, 6.0000, 2.5000],
         [5.1000, 3.8000, 1.5000, 0.3000],
         [5.4000, 3.0000, 4.5000, 1.5000],
         [5.6000, 3.0000, 4.5000, 1.5000],
         [4.7000, 3.2000, 1.6000, 0.2000],
         [5.1000, 3.5000, 1.4000, 0.3000],
         [7